# Generated by Django 5.1.3 on 2024-11-25 05:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('password_manage', '0002_alter_passwordmanage_site_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='passwordmanage',
            name='site_name',
            field=models.CharField(max_length=255, verbose_name='Site Name'),
        ),
    ]
